[http_service]
force_https = true
min_machines_running = 0

[http_service.http_options]
h2_backend = true

[[http_service.checks]]
path = "/"
method = "HEAD"
timeout = "60s"
grace_period = "10s"
interval = "10s"
[http_service.checks.headers]
Referer = "https://x/?x_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[[files]]
guest_path = "/usr/local/etc/xray/config.json"
local_path = "config.json"

[build]
image = "ghcr.io/xtls/xray-core"
